### ISSUE TITLE
Rendering of Claimed Chunks fails after disabling it once

### ISSUE THREAD

**Issue by Arbee4ever** [KosmosPrime/journey-pac#3]
I installed your mod, but when I disabled it once I couldn't reenable it again and I get this error in the logs: 
```
[12:59:48] [Render thread/ERROR]: Error displaying claimed chunks
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1625) ~[?:?]
	at journeypac.JourneymapPlugin.showClaims(JourneymapPlugin.java:443) ~[transformed-mod-journeypac.i0:0/:?]
	at journeypac.JourneymapPlugin.onToggleClaims(JourneymapPlugin.java:338) ~[transformed-mod-journeypac.i0:0/:?]
	at journeymap.client.api.impl.ThemeFactory.lambda$getThemeToggleButton$2(ThemeFactory.java:30) ~[transformed-mod-journeymap.i0:0/:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:43) ~[transformed-mod-minecraft.i0:0/:?]
	at journeymap.client.ui.component.Button.method_25306(Button.java:423) ~[transformed-mod-journeymap.i0:0/:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:120) ~[transformed-mod-minecraft.i0:0/:?]
	at journeymap.client.ui.component.Button.method_25402(Button.java:452) ~[transformed-mod-journeymap.i0:0/:?]
	at journeymap.client.ui.theme.ThemeToggle.method_25402(ThemeToggle.java:43) ~[transformed-mod-journeymap.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[transformed-mod-minecraft.i0:0/:?]
	at journeymap.client.ui.fullscreen.Fullscreen.method_25402(Fullscreen.java:1105) ~[transformed-mod-journeymap.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:489) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[transformed-mod-minecraft.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) [lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:315) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1205) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [transformed-mod-minecraft.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) [quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) [quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
```
I'm using quilt 0.19.2 and JourneyPAC 1.1.5

**Comment by Arbee4ever** [comment]
restarting fixed it

**Comment by KosmosPrime** [comment]
Unable to reproduce but the error is quite obvious. Is it possible that someone was claiming chunks or were you changing dimensions at the same time as you've toggled the claimed chunks overlay?

**Comment by Arbee4ever** [comment]
No, I was alone on the server and stood around in the overworld.
