### ISSUE TITLE
JourneyMap version number issue

### ISSUE THREAD

**Issue by cai-tan** [KosmosPrime/journey-pac#7]
When using with the latest JourneyMap version, this error occurs:
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Journeymap' (journeymap) 5.9.18p1 with version 5.9.8 or later.
More details:
	 - Mod 'JourneyPAC' (journeypac) 1.1.5 requires version 5.9.8 or later of mod 'Journeymap' (journeymap), but only the wrong version is present: 5.9.18p1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
I know this is more or less a Fabric issue and/or a "TeamJM decided to break version numbering convention" issue but a bandaid fix could be to just make a patch that targets 18p1 for now.

**Comment by KosmosPrime** [comment]
Truly a strange choice given that semver has a build specifier that would not have broken compatibility. Anyway, the immediate workaround is to use fabric's [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides) for select versions (unless you can edit the jars themselves of course).
I'll hold off adding this one to the list until I know whether it's a fluke or a trend, if they keep doing it I'll just drop the version requirement instead and hope it doesn't cause issues.
